Reworked extra stat implementation
kdreese/gmtk-2023 pull request #63
Opened 2023-11-02 03:58 UTC by kdreese

2023-11-10 00:05 UTC, admoore0 requested changes

2023-11-10 00:05 UTC, admoore0 commented on src/states/game/game.gd
> +
So I've been thinking about how to clean this up, and I think I've come up with a good solution. Basically we would split up extra stats into two:

Unit Buffs:
- apply to individual units
- stored in `extra_stats`
- always get cleared right before the next turn begins

Tile Buffs:
- Only for battering ram right now
- Stored in the `DropPoint` class, similar to `extra_data` is for Units
- Updated whenever a battering ram is placed (add the buff to the right squares) or moves (subtract the buff from previous squares, add to new ones)

When evaluating the extra stats for attacking or for the tooltip, sum the two together

Does this seem alright?

2023-11-10 00:05 UTC, admoore0 commented on src/states/game/game.gd
> +	can_display_tooltip = false
Nice.

2023-11-10 00:05 UTC, admoore0 commented on src/ui/tooltip.gd
> +	position.x = clampf(position.x, -100 + size.x / 2, 740 - size.x / 2)
I really wish there was a better way for this, not worth the effort right now though.

2023-11-16 03:22 UTC, admoore0 requested changes
Just a few minor things

2023-11-16 03:22 UTC, admoore0 commented on src/cards/actions/lightning.gd
> +			unit.commit_die()
me when i 💀

2023-11-16 03:22 UTC, admoore0 commented on src/states/game/game.gd
> +			unit.extra_stats.erase(stat)
Could probably just do `unit.extra_stats = {}`

2023-11-16 03:22 UTC, admoore0 commented on src/states/game/game.gd
> +		pass
Remove

2023-11-16 03:52 UTC, admoore0 approved these changes, later dismissed

2023-11-16 04:14 UTC, thearst3rd requested changes
I'm a pedant sorry D:

2023-11-16 04:14 UTC, thearst3rd commented on src/states/game/game.gd
> +				drop_point.extra_stats["attack_power"] = 0
This is totally valid. Worth noting, we can also just omit these lines since it won't do anything

2023-11-16 04:14 UTC, thearst3rd commented on src/states/game/game.gd
> +	# apply battering ram on attack
#pedantic: Capitalize "Apply"

2023-11-16 04:14 UTC, thearst3rd commented on src/ui/tooltip.gd
> +	if(unit.extra_stats.get(stat_name, 0)):
#pedantic: Remove unneeded parens
```suggestion
	if unit.extra_stats.get(stat_name, 0):
```

2023-11-16 04:14 UTC, thearst3rd commented on src/units/unit.gd
> +var card_data: CardData
god bless

2023-11-16 04:14 UTC, thearst3rd commented on src/states/game/game.gd
> +				drop_point.extra_stats["attack_power"] -= int(unit.card_data.extra_data[0])
Maybe we should add a bounds check right after, something like:
```gdscript
drop_point.extra_stats["attack_power"] -= int(unit.card_data.extra_data[0])
if drop_point.extra_stats["attack_power"] <= 0:
    drop_point.extra_stats.erase("attack_power")
```

2023-11-16 04:14 UTC, thearst3rd commented on src/states/game/game.gd
> +				drop_point.extra_stats["attack_power"] -= int(unit.card_data.extra_data[0])
Nevermind, it is possible we may want to intentionally allow the attack power to go below zero as a debuff.

2023-11-16 04:18 UTC, thearst3rd approved these changes

2023-11-16 04:18 UTC, merged